export default [
  {
    title: "Porshe 718 Cayman S",
    subtitle: "Coupe",
    seats: 4,
    gear: "Manual",
    price: "400",
  },
  {
    title: "Porshe 718 Cayman S",
    subtitle: "Coupe",
    seats: 4,
    gear: "Manual",
    price: "400",
    liked: true,
  },
  {
    title: "Porshe 718 Cayman S",
    subtitle: "Coupe",
    seats: 4,
    gear: "Manual",
    price: "400",
  },
  {
    title: "Porshe 718 Cayman S",
    subtitle: "Coupe",
    seats: 4,
    gear: "Manual",
    price: "400",
  },
  {
    title: "Porshe 718 Cayman S",
    subtitle: "Coupe",
    seats: 4,
    gear: "Manual",
    price: "400",
  },
  {
    title: "Porshe 718 Cayman S",
    subtitle: "Coupe",
    seats: 4,
    gear: "Manual",
    price: "400",
  },
  {
    title: "Porshe 718 Cayman S",
    subtitle: "Coupe",
    seats: 4,
    gear: "Manual",
    price: "400",
  },
  {
    title: "Porshe 718 Cayman S",
    subtitle: "Coupe",
    seats: 4,
    gear: "Manual",
    price: "400",
  },
  {
    title: "Porshe 718 Cayman S",
    subtitle: "Coupe",
    seats: 4,
    gear: "Manual",
    price: "400",
  },
];
